### ISSUE TITLE
Auto rotate not working on OP 7 Pro.

### ISSUE THREAD

**Issue by Str3la** [LineageOS/android_device_oneplus_guacamole#1]
Tested it out on the latest build 20200215 and it still doesn't work. The OS doesn't detect the sensor it seems. I've read somewhere that there is a workaround if an old Oxygen OS is flashed first and then over it Lineage OS it should work but don't recall how old the version of OOS should be. I can live without auto rotate for a while even though a bit inconvenient, will wait for the fix.

I am not sure if you're aware of this just bringing it to your attention since a lot of people later on, if they switch to Lineage will have trouble with it.

**Comment by luk1337** [comment]
https://gitlab.com/LineageOS/issues/android/issues/1522#note_274265612

**Comment by Str3la** [comment]
Yes, that is the thread I read. But that is that the final solution? Because I remember there was no vendor image or something a while back so you had to flash lineage over OOS and now there is. Is there any plans to do the same with sensors? I don't mind waiting around and testing it when you roll it out. See if it has any bugs for people who will switch later on.

**Comment by luk1337** [comment]
Just do what the post says.

**Comment by luk1337** [comment]
Just do what the post says.

**Comment by Str3la** [comment]
I know it will work. Just so long as you know that its there its fine I guess.
